### ISSUE TITLE
Kemono new domain Trouble

### ISSUE THREAD

**Issue by lukmanscootkenn** [ovear/kemono-dl#18]
### Version

Version: 2022.04.28

### Your Command

```bash

python kemono-dl.py --user-agent curl/7.66.0 --post-timeout 1 --retry 10 --cookies "cookie.txt" --links https://kemono.su/patreon/user/50815354 --filename-pattern "[{published}] {title}_{index}.{ext}" --date-strf-pattern "%Y-%m-%d" --skip-filetypes psd,

```

### Description of bug

ERROR:Unable to get list of creators from kemono.su
ERROR:No creator information was retrieved. | exiting

### How To Reproduce

running the script normally after update the cookies and update the file source from github

### Error messages and tracebacks

```python

ERROR:Unable to get list of creators from kemono.su
Traceback (most recent call last):
  File "C:\Users\Lukman Scoot Kennedy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\Downloader\kemono-dl-main\src\main.py", line 673, in start_download
    self.creators += self.get_creators(domain)
  File "Z:\Downloader\kemono-dl-main\src\main.py", line 105, in get_creators
    return self.session.get(url=creators_api, cookies=self.cookies, headers=self.headers, timeout=self.timeout).json()
  File "C:\Users\Lukman Scoot Kennedy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
: 0
ERROR:No creator information was retrieved. | exiting

```

### Additional comments

after kemono switching domain from .party into .su , i try to update the cookies and the script into latest one...and when i try to run the script like i was before...the error pops out

**Comment by Fluboxer** [comment]
Came here with same problem

https://github.com/Ovear/kemono-dl/pull/19 solves everything

**Comment by Ovear** [comment]
Hi,

This is caused by api break change of kemono. This latest version should fix it. And thanks @Kerisa for letting me know this.
